cflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cflix/superadmin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace="admin_honeypot")),
    path('', include('main.urls')),
    path('video/', include('videos.urls')),
    path('audio/', include('music.urls')),
]

handler404 = 'errors.views.h404'
handler500 = 'errors.views.h500'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import loginUser, logoutUser, home, profile, dashboard, registerUser, settings, search, videos, music

app_name="main"
urlpatterns = [
    path('', home, name="home"),
    path('login/', loginUser, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('register/', registerUser, name="register"),
    path('dashboard/', dashboard, name="dash"),
    path('search/', search, name="search"),
    path('video/', videos, name="videos"),
    path('audio/', music, name="music"),
    path('settings/', settings, name="settings"),
    path('profile/', profile, name="profile"),
]

templates/layouts/auth.layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7c743f70a9.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.png' %}" alt="" width="30"
                        height="24" class="d-inline-block align-text-top">
                    CFlix
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:videos' %}">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:music' %}">Music</a>
                        </li>
                    </ul>
                    <form action="{% url 'main:search' %}" method="POST" class="d-flex ms-auto me-auto">
                        {% csrf_token %}
                        <input class="form-control me-2" name="query" type="search"
                            placeholder="Search for movies and music" aria-label="Search">
                        <button class="btn btn-warning" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                            <a class="btn btn-danger" href="{% url 'main:logout' %}">Logout</a>
                            {% else %}
                            <a class="btn btn-primary" href="{% url 'main:login' %}">Login</a>
                            <strong class="text-white"> OR </strong>
                            <a class="btn btn-success" href="{% url 'main:register' %}">Register</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav><br>
    </header>
    <main>
        <div class="container">
            {% include 'layouts/messages.html' %}
        </div>
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
        <script>
            const options = {
                label: '🌓'
            }
            function addDarkmodeWidget() {
                new Darkmode(options).showWidget();
            }
            window.addEventListener('load', addDarkmodeWidget);
        </script>

    </footer>
</body>

</html>

templates/layouts/main.layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/7c743f70a9.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{% static 'img/logo.png' %}" alt="" width="30"
                        height="24" class="d-inline-block align-text-top">
                    CFlix
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:videos' %}">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:music' %}">Music</a>
                        </li>
                    </ul>
                    <form action="{% url 'main:search' %}" method="POST" class="d-flex ms-auto me-auto">
                        {% csrf_token %}
                        <input class="form-control me-2" name="query" type="search"
                            placeholder="Search for movies and music" aria-label="Search">
                        <button class="btn btn-warning" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Welcome, <strong class="text-white"> {{ user.first_name }} {{ user.last_name }}
                                </strong>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'main:settings' %}"><i
                                            class="fas fa-cogs"></i> Settings</a></li>
                                <li><a class="dropdown-item" href="{% url 'main:profile' %}"><i class="fas fa-user"></i>
                                        Profile</a></li>
                                <li><a href="{% url 'main:logout' %}" class="dropdown-item"><i
                                            class="fas fa-sign-out-alt"></i> Logout</a></li>
                            </ul>
                        </li>
                        {% endif %}
                        <li class="nav-item">
                            {% if not user.is_authenticated %}
                            <a class="btn btn-primary" href="{% url 'main:login' %}">Login</a>
                            <strong class="text-white"> OR </strong>
                            <a class="btn btn-success" href="{% url 'main:register' %}">Register</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav><br>
    </header>
    <main>
        <div class="container">
            {% include 'layouts/messages.html' %}
        </div>
        {% block body %}
        {% endblock %}
    </main>
    <footer>
        <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
        <script>
            const options = {
                label: '🌓'
            }
            function addDarkmodeWidget() {
                new Darkmode(options).showWidget();
            }
            window.addEventListener('load', addDarkmodeWidget);
        </script>

    </footer>
</body>

</html>

templates/layouts/messages.html
{% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <strong>{{ message }}</strong>
  </div>
</div>
{% endfor %}